version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql

  backend:
    build:
      context: .
      dockerfile: recipe-app-backend/Dockerfile
    ports:
      - "5000:5000"
    environment:
      DB_USER: ${DB_USER}
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: 5432
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: recipe-site-frontend/Dockerfile
    ports:
      - "3000:80"


volumes:
  postgres_data:
